"""Config command module."""
import os
from pathlib import Path
from typing import Optional

import typer
from rich.console import Console
from rich.table import Table

from ...config import Settings

app = typer.Typer(
    name="config",
    help="Manage configuration",
)

console = Console()

# Define config keys that are safe to display/modify
# Exclude sensitive keys like secret_key
CONFIG_KEYS = [
    "database_url",
    "redis_url",
    "api_host",
    "api_port",
    "api_workers",
    "dramatiq_broker_url",
    "dramatiq_max_retries",
    "dramatiq_retry_delay",
    "scheduler_enabled",
    "default_fetch_interval",
    "log_level",
    "log_file",
    "api_token_expire_minutes",
]

SENSITIVE_KEYS = {"secret_key", "database_url", "redis_url", "dramatiq_broker_url"}

DEFAULTS = {
    "database_url": "postgresql://localhost/cyberpulse",
    "redis_url": "redis://localhost:6379/0",
    "api_host": "0.0.0.0",
    "api_port": "8000",
    "api_workers": "4",
    "dramatiq_broker_url": "redis://localhost:6379/1",
    "dramatiq_max_retries": "3",
    "dramatiq_retry_delay": "60",
    "scheduler_enabled": "True",
    "default_fetch_interval": "3600",
    "log_level": "INFO",
    "log_file": "logs/cyberpulse.log",
    "secret_key": "change-this-to-a-random-secret-key",
    "api_token_expire_minutes": "1440",
}


def _get_env_file_path() -> Path:
    """Get the path to the .env file."""
    # Check current directory first, then parent directories
    env_path = Path(".env")
    if env_path.exists():
        return env_path.resolve()

    # Check parent directories up to 3 levels
    for i in range(1, 4):
        parent_env = Path.cwd().parents[i - 1] / ".env" if i <= len(Path.cwd().parents) else None
        if parent_env and parent_env.exists():
            return parent_env

    # Default to current directory .env
    return Path.cwd() / ".env"


def _read_env_file(path: Path) -> dict[str, str]:
    """Read environment variables from .env file."""
    env_vars: dict[str, str] = {}
    if not path.exists():
        return env_vars

    with open(path) as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                key, _, value = line.partition("=")
                env_vars[key.strip()] = value.strip().strip('"').strip("'")
    return env_vars


def _write_env_file(path: Path, env_vars: dict[str, str]) -> None:
    """Write environment variables to .env file."""
    with open(path, "w") as f:
        f.write("# cyber-pulse configuration\n")
        f.write("# Generated by cyber-pulse config commands\n\n")
        for key, value in sorted(env_vars.items()):
            # Quote values that contain spaces or special characters
            if " " in value or "#" in value or value.startswith('"') or value.startswith("'"):
                f.write(f'{key}="{value}"\n')
            else:
                f.write(f"{key}={value}\n")


def _mask_sensitive_value(key: str, value: str) -> str:
    """Mask sensitive values for display."""
    if key in SENSITIVE_KEYS and value:
        # Show first 10 characters, mask the rest
        if len(value) > 15:
            return f"{value[:10]}...{value[-4:]}"
        return "***"
    return value


@app.command("get")
def get_config(key: str) -> None:
    """Get a configuration value.

    Args:
        key: Configuration key name (e.g., database_url, log_level)
    """
    key_lower = key.lower()

    if key_lower not in CONFIG_KEYS and key_lower not in DEFAULTS:
        console.print(f"[red]Error:[/red] Unknown configuration key: {key}")
        console.print(f"[dim]Valid keys: {', '.join(CONFIG_KEYS)}[/dim]")
        raise typer.Exit(1)

    # Get value from current settings
    settings = Settings()
    value = getattr(settings, key_lower, None)

    if value is None:
        console.print(f"[yellow]Configuration '{key}' is not set[/yellow]")
    else:
        masked = _mask_sensitive_value(key_lower, str(value))
        console.print(f"{key} = [green]{masked}[/green]")


@app.command("set")
def set_config(
    key: str,
    value: str,
    env_file: Optional[Path] = typer.Option(
        None, "--env-file", "-e", help="Path to .env file (default: ./env)"
    ),
) -> None:
    """Set a configuration value.

    This command writes the value to the .env file for persistence.

    Args:
        key: Configuration key name (e.g., log_level, api_port)
        value: Configuration value
        env_file: Optional path to .env file
    """
    key_lower = key.lower()

    if key_lower not in CONFIG_KEYS:
        console.print(f"[red]Error:[/red] Unknown configuration key: {key}")
        console.print(f"[dim]Valid keys: {', '.join(CONFIG_KEYS)}[/dim]")
        raise typer.Exit(1)

    # Validate certain keys
    if key_lower == "log_level" and value.upper() not in (
        "DEBUG",
        "INFO",
        "WARNING",
        "ERROR",
        "CRITICAL",
    ):
        console.print(f"[red]Error:[/red] Invalid log level: {value}")
        console.print("[dim]Valid levels: DEBUG, INFO, WARNING, ERROR, CRITICAL[/dim]")
        raise typer.Exit(1)

    # Determine .env file path
    env_path = env_file if env_file else _get_env_file_path()

    # Read existing env file
    env_vars = _read_env_file(env_path)

    # Update the key
    env_vars[key_lower] = value

    # Write back
    try:
        _write_env_file(env_path, env_vars)
        masked = _mask_sensitive_value(key_lower, value)
        console.print(f"[green]Set {key} = {masked}[/green]")
        console.print(f"[dim]Written to: {env_path}[/dim]")
        console.print("[yellow]Note:[/yellow] Restart the application for changes to take effect")
    except Exception as e:
        console.print(f"[red]Error writing to .env file:[/red] {e}")
        raise typer.Exit(1)


@app.command("list")
def list_config(
    show_secrets: bool = typer.Option(
        False, "--show-secrets", "-s", help="Show sensitive values (use with caution)"
    )
) -> None:
    """List all configuration values.

    Args:
        show_secrets: Whether to show sensitive values like passwords and secrets
    """
    settings = Settings()

    table = Table(title="Configuration")
    table.add_column("Key", style="cyan")
    table.add_column("Value", style="green")
    table.add_column("Default", style="dim")
    table.add_column("Source", style="yellow")

    for key in CONFIG_KEYS:
        value = getattr(settings, key, None)
        default = DEFAULTS.get(key, "")

        # Determine source
        env_value = os.environ.get(key.upper())
        if env_value is not None:
            source = "env"
        elif key in _read_env_file(_get_env_file_path()):
            source = ".env"
        else:
            source = "default"

        # Format value for display
        if value is not None:
            display_value = str(value)
            if not show_secrets:
                display_value = _mask_sensitive_value(key, display_value)
        else:
            display_value = "[dim]not set[/dim]"

        table.add_row(
            key,
            display_value,
            _mask_sensitive_value(key, default) if not show_secrets else default,
            source,
        )

    console.print(table)


@app.command("reset")
def reset_config(
    key: Optional[str] = typer.Argument(None, help="Configuration key to reset (omit to reset all)"),
    env_file: Optional[Path] = typer.Option(
        None, "--env-file", "-e", help="Path to .env file (default: ./.env)"
    ),
    force: bool = typer.Option(False, "--force", "-f", help="Skip confirmation prompt"),
) -> None:
    """Reset configuration to defaults.

    This command removes keys from the .env file, reverting to default values.

    Args:
        key: Optional specific key to reset (omit to reset all)
        env_file: Optional path to .env file
        force: Skip confirmation prompt
    """
    env_path = env_file if env_file else _get_env_file_path()

    if not env_path.exists():
        console.print("[yellow]No .env file found. Configuration already at defaults.[/yellow]")
        return

    env_vars = _read_env_file(env_path)

    if key:
        # Reset specific key
        key_lower = key.lower()
        if key_lower not in CONFIG_KEYS:
            console.print(f"[red]Error:[/red] Unknown configuration key: {key}")
            console.print(f"[dim]Valid keys: {', '.join(CONFIG_KEYS)}[/dim]")
            raise typer.Exit(1)

        if key_lower not in env_vars:
            console.print(f"[yellow]Configuration '{key}' is not set in .env file[/yellow]")
            return

        del env_vars[key_lower]
        _write_env_file(env_path, env_vars)
        console.print(f"[green]Reset {key} to default value[/green]")
        console.print(f"[dim]Updated: {env_path}[/dim]")
    else:
        # Reset all keys
        keys_to_reset = [k for k in env_vars if k.lower() in CONFIG_KEYS]

        if not keys_to_reset:
            console.print("[yellow]No configuration keys found in .env file[/yellow]")
            return

        if not force:
            console.print(f"[yellow]This will reset {len(keys_to_reset)} configuration key(s) to defaults:[/yellow]")
            for k in keys_to_reset:
                console.print(f"  - {k}")

            confirm = typer.confirm("Continue?", default=False)
            if not confirm:
                console.print("[dim]Cancelled[/dim]")
                raise typer.Exit(0)

        for k in keys_to_reset:
            del env_vars[k.lower()]

        _write_env_file(env_path, env_vars)
        console.print(f"[green]Reset {len(keys_to_reset)} configuration key(s) to defaults[/green]")
        console.print(f"[dim]Updated: {env_path}[/dim]")

    console.print("[yellow]Note:[/yellow] Restart the application for changes to take effect")