"""add full fetch fields

Revision ID: 810a2d7751de
Revises: b88fa801bab2
Create Date: 2026-03-26 07:04:19.935747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '810a2d7751de'
down_revision: Union[str, Sequence[str], None] = 'b88fa801bab2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('full_fetch_attempted', sa.Boolean(), nullable=False))
    op.add_column('items', sa.Column('full_fetch_succeeded', sa.Boolean(), nullable=True))
    op.add_column('sources', sa.Column('needs_full_fetch', sa.Boolean(), nullable=False))
    op.add_column('sources', sa.Column('full_fetch_threshold', sa.Float(), nullable=True))
    op.add_column('sources', sa.Column('content_type', sa.String(length=20), nullable=True))
    op.add_column('sources', sa.Column('avg_content_length', sa.Integer(), nullable=True))
    op.add_column('sources', sa.Column('quality_score', sa.Float(), nullable=True))
    op.add_column('sources', sa.Column('full_fetch_success_count', sa.Integer(), nullable=False))
    op.add_column('sources', sa.Column('full_fetch_failure_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'full_fetch_failure_count')
    op.drop_column('sources', 'full_fetch_success_count')
    op.drop_column('sources', 'quality_score')
    op.drop_column('sources', 'avg_content_length')
    op.drop_column('sources', 'content_type')
    op.drop_column('sources', 'full_fetch_threshold')
    op.drop_column('sources', 'needs_full_fetch')
    op.drop_column('items', 'full_fetch_succeeded')
    op.drop_column('items', 'full_fetch_attempted')
    # ### end Alembic commands ###
